### ISSUE TITLE
mkdir(): Invalid path in ./vendor/hyperf/view-engine/src/Factory/FinderFactory.php:32

### ISSUE THREAD

**Issue by harryqt** [swooletw/hyperf-packages#34]
### OS

MacOS 14

### PHP Version

8.3.11

### Swoole Extension Version

5.1.4

### Description

```
~/Projects/example-laravel-hyperf- php hyperf serve                                                                        ✔ 
[INFO] Worker#4 started.
[INFO] Worker#0 started.
[INFO] Worker#1 started.
[INFO] Worker#2 started.
[INFO] HTTP Server listening at 0.0.0.0:9501
[INFO] Worker#5 started.
[INFO] Worker#6 started.
[INFO] Worker#3 started.
[INFO] Worker#7 started.
[CRITICAL] ErrorException: mkdir(): Invalid path in /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/view-engine/src/Factory/FinderFactory.php:32
Stack trace:
#0 [internal function]: Hyperf\ExceptionHandler\Listener\ErrorExceptionHandler::Hyperf\ExceptionHandler\Listener\{closure}(2, 'mkdir(): Invali...', '/Users/harry/Pr...', 32)
#1 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/view-engine/src/Factory/FinderFactory.php(32): mkdir('', 493, true)
#2 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/di/src/Resolver/FactoryResolver.php(46): Hyperf\ViewEngine\Factory\FinderFactory->__invoke(Object(SwooleTW\Hyperf\Foundation\Application), Array)
#3 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(51): Hyperf\Di\Resolver\FactoryResolver->resolve(Object(Hyperf\Di\Definition\FactoryDefinition), Array)
#4 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/di/src/Resolver/DepthGuard.php(68): Hyperf\Di\Resolver\ResolverDispatcher->Hyperf\Di\Resolver\{closure}()
#5 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(49): Hyperf\Di\Resolver\DepthGuard->call('Hyperf\\ViewEngi...', Object(Closure))
#6 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/di/src/Container.php(161): Hyperf\Di\Resolver\ResolverDispatcher->resolve(Object(Hyperf\Di\Definition\FactoryDefinition), Array)
#7 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/di/src/Container.php(62): Hyperf\Di\Container->resolveDefinition(Object(Hyperf\Di\Definition\FactoryDefinition), Array)
#8 /Users/harry/Projects/example-laravel-hyperf/vendor/swooletw/hyperf-packages/src/container/src/Container.php(120): Hyperf\Di\Container->make('Hyperf\\ViewEngi...', Array)
#9 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/di/src/Container.php(103): SwooleTW\Hyperf\Container\Container->make('Hyperf\\ViewEngi...')
#10 /Users/harry/Projects/example-laravel-hyperf/vendor/swooletw/hyperf-packages/src/container/src/Container.php(145): Hyperf\Di\Container->get('Hyperf\\ViewEngi...')
#11 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/di/src/Definition/Reference.php(64): SwooleTW\Hyperf\Container\Container->get('Hyperf\\ViewEngi...')
#12 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(44): Hyperf\Di\Definition\Reference->resolve(Object(SwooleTW\Hyperf\Foundation\Application))
#13 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/di/src/Resolver/ParameterResolver.php(64): Hyperf\Di\Resolver\ResolverDispatcher->resolve(Object(Hyperf\Di\Definition\Reference))
#14 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/di/src/Resolver/ObjectResolver.php(84): Hyperf\Di\Resolver\ParameterResolver->resolveParameters(Object(Hyperf\Di\Definition\MethodInjection), Object(ReflectionMethod), Array)
#15 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/di/src/Resolver/ObjectResolver.php(52): Hyperf\Di\Resolver\ObjectResolver->createInstance(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#16 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(51): Hyperf\Di\Resolver\ObjectResolver->resolve(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#17 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/di/src/Resolver/DepthGuard.php(68): Hyperf\Di\Resolver\ResolverDispatcher->Hyperf\Di\Resolver\{closure}()
#18 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(49): Hyperf\Di\Resolver\DepthGuard->call('Hyperf\\ViewEngi...', Object(Closure))
#19 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/di/src/Container.php(161): Hyperf\Di\Resolver\ResolverDispatcher->resolve(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#20 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/di/src/Container.php(62): Hyperf\Di\Container->resolveDefinition(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#21 /Users/harry/Projects/example-laravel-hyperf/vendor/swooletw/hyperf-packages/src/container/src/Container.php(120): Hyperf\Di\Container->make('Hyperf\\ViewEngi...', Array)
#22 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/di/src/Container.php(103): SwooleTW\Hyperf\Container\Container->make('Hyperf\\ViewEngi...')
#23 /Users/harry/Projects/example-laravel-hyperf/vendor/swooletw/hyperf-packages/src/container/src/Container.php(145): Hyperf\Di\Container->get('Hyperf\\ViewEngi...')
#24 /Users/harry/Projects/example-laravel-hyperf/vendor/swooletw/hyperf-packages/src/support/src/Facades/Facade.php(175): SwooleTW\Hyperf\Container\Container->get('Hyperf\\ViewEngi...')
#25 /Users/harry/Projects/example-laravel-hyperf/vendor/swooletw/hyperf-packages/src/support/src/Facades/Facade.php(158): SwooleTW\Hyperf\Support\Facades\Facade::resolveFacadeInstance('Hyperf\\ViewEngi...')
#26 /Users/harry/Projects/example-laravel-hyperf/vendor/swooletw/hyperf-packages/src/support/src/Facades/Facade.php(144): SwooleTW\Hyperf\Support\Facades\Facade::getFacadeRoot()
#27 /Users/harry/Projects/example-laravel-hyperf/vendor/swooletw/hyperf-packages/src/foundation/src/Exceptions/RegisterErrorViewPaths.php(16): SwooleTW\Hyperf\Support\Facades\Facade::__callStatic('replaceNamespac...', Array)
#28 /Users/harry/Projects/example-laravel-hyperf/vendor/swooletw/hyperf-packages/src/foundation/src/Exceptions/Handler.php(794): SwooleTW\Hyperf\Foundation\Exceptions\RegisterErrorViewPaths->__invoke()
#29 /Users/harry/Projects/example-laravel-hyperf/vendor/swooletw/hyperf-packages/src/foundation/src/Exceptions/Handler.php(139): SwooleTW\Hyperf\Foundation\Exceptions\Handler->registerErrorViewPaths()
#30 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/di/src/Resolver/ObjectResolver.php(85): SwooleTW\Hyperf\Foundation\Exceptions\Handler->__construct(Object(SwooleTW\Hyperf\Foundation\Application))
#31 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/di/src/Resolver/ObjectResolver.php(52): Hyperf\Di\Resolver\ObjectResolver->createInstance(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#32 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(51): Hyperf\Di\Resolver\ObjectResolver->resolve(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#33 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/di/src/Resolver/DepthGuard.php(68): Hyperf\Di\Resolver\ResolverDispatcher->Hyperf\Di\Resolver\{closure}()
#34 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(49): Hyperf\Di\Resolver\DepthGuard->call('App\\Exceptions\\...', Object(Closure))
#35 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/di/src/Container.php(161): Hyperf\Di\Resolver\ResolverDispatcher->resolve(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#36 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/di/src/Container.php(62): Hyperf\Di\Container->resolveDefinition(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#37 /Users/harry/Projects/example-laravel-hyperf/vendor/swooletw/hyperf-packages/src/container/src/Container.php(120): Hyperf\Di\Container->make('App\\Exceptions\\...', Array)
#38 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/di/src/Container.php(103): SwooleTW\Hyperf\Container\Container->make('App\\Exceptions\\...')
#39 /Users/harry/Projects/example-laravel-hyperf/vendor/swooletw/hyperf-packages/src/container/src/Container.php(145): Hyperf\Di\Container->get('App\\Exceptions\\...')
#40 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/exception-handler/src/ExceptionHandlerDispatcher.php(40): SwooleTW\Hyperf\Container\Container->get('App\\Exceptions\\...')
#41 /Users/harry/Projects/example-laravel-hyperf/vendor/swooletw/hyperf-packages/src/foundation/src/Http/Kernel.php(113): Hyperf\ExceptionHandler\ExceptionHandlerDispatcher->dispatch(Object(ErrorException), Array)
#42 /Users/harry/Projects/example-laravel-hyperf/vendor/hyperf/support/src/SafeCaller.php(30): SwooleTW\Hyperf\Foundation\Http\Kernel->SwooleTW\Hyperf\Foundation\Http\{closure}()
#43 /Users/harry/Projects/example-laravel-hyperf/vendor/swooletw/hyperf-packages/src/foundation/src/Http/Kernel.php(112): Hyperf\Support\SafeCaller->call(Object(Closure), Object(Closure))
#44 /Users/harry/Projects/example-laravel-hyperf/vendor/swooletw/hyperf-packages/src/foundation/src/Http/Kernel.php(56): SwooleTW\Hyperf\Foundation\Http\Kernel->getResponseForException(Object(ErrorException))
#45 [internal function]: SwooleTW\Hyperf\Foundation\Http\Kernel->onRequest(Object(Swoole\Http\Request), Object(Swoole\Http\Response))
#46 {main}
```

### Steps To Reproduce

```
composer create-project swooletw/laravel-hyperf example-laravel-hyperf dev-master
php hyperf serve
```

Then open: http://localhost:9501

**Comment by harryqt** [comment]
[`Blade::config('config.cache_path')`](https://github.com/hyperf/hyperf/blob/master/src/view-engine/src/Factory/FinderFactory.php#L30) returns empty string

**Comment by albertcht** [comment]
Hi @harryqt ,

Can you please try to run with Swoole 5.1.2 or 5.1.3?
One of my team members reported this issue few days ago. And I'm verifying if it only happened on Swoole 5.1.4.

**Comment by harryqt** [comment]
I don't think it has anything to do with swoole version. On the `__invoke()` method in [FinderFactory.php#L22](https://github.com/hyperf/hyperf/blob/e05fe2478b544640af68745fa7a7bfe5f920b38a/src/view-engine/src/Factory/FinderFactory.php#L22) if I add:

```php
var_dump(config('view.config.view_path')); //this returns NULL
```

 and restart server and reload page, I see `NULL` on console. That basically means `config('view.config.view_path')` for some reason not resolving correctly.

However, on `php hyperf tinker` it works correctly.

```sh
config('view.config.view_path') //returns /Users/harry/Projects/example-laravel-hyperf/resources/views
```

**Comment by harryqt** [comment]
```php
Route::get('/', function () {
    // return view('welcome');
    var_dump(config('view.config.view_path')); // NULL in console
});
```

**Comment by harryqt** [comment]
```php
use SwooleTW\Hyperf\Support\Facades\Route;
use Hyperf\Context\ApplicationContext;
use Hyperf\Contract\ConfigInterface;

Route::get('/', function () {
    // var_dump(\SwooleTW\Hyperf\Config\config('view.config.view_path'));
    
    $config = ApplicationContext::getContainer()->get(ConfigInterface::class);
    print_r($config);
});
```

values of `config/views.php` are not available `$config`, thus failing.

<img width="1582" alt="Screenshot 2024-09-18 at 2 26 37 AM" src="https://github.com/user-attachments/assets/6da1fef4-a5c6-43d4-bfe9-bc240e3afadb">

**Comment by harryqt** [comment]
`config()` is the culprit here, returns `NULL`

```php
Route::get('/', function () {
    var_dump(config('view.config.view_path')); // returns NULL
});
```

That is happening because values from `config/views.php` are not appending.

```php
Route::get('/', function () {
    $config = ApplicationContext::getContainer()->get(ConfigInterface::class);
    var_dump($config);
});
```

<img width="1582" alt="Screenshot 2024-09-18 at 2 59 19 AM" src="https://github.com/user-attachments/assets/ca84554c-2316-45ab-a1f6-9c623e20d75d">

**Comment by harryqt** [comment]
cc @albertcht

**Comment by harryqt** [comment]
Temporary fix:

`config/hyperf.php`
```php
<?php

declare(strict_types=1);

use Hyperf\View\Mode;
use Hyperf\ViewEngine\HyperfViewEngine;

return [
    'view' => [
        'engine' => HyperfViewEngine::class,
        'mode' => Mode::SYNC,
        'config' => [
            'view_path' => base_path('resources/views'),
            'cache_path' => storage_path('framework/views'),
        ]
    ]
];

```

**Comment by storyn26383** [comment]
Hi @harryqt, I encountered the same problem as you.
After some research, I discovered that Swoole's coroutine was causing the issue.
There is a simple program that reproduces the problem:

```
<?php

Swoole\Runtime::enableCoroutine(true);

var_dump(scandir(__DIR__));
```

You'll notice that when the coroutine is enabled, `scandir` returns an empty array, which prevents the framework from finding the config files, thus causing this error.
This morning, I upgraded my Mac to version 15 and reinstalled Swoole, which resolved the issue.

**Comment by harryqt** [comment]
What’s your Swoole and Php version?

**Comment by harryqt** [comment]
Upgraded to MacOS 15, but same error.

**Comment by harryqt** [comment]
Reinstalling solved the issue. 🤷

```
brew reinstall swoole@8.3
```
